apiVersion: apps/v1
kind: Deployment
metadata:
  name: comin-leave-management-service
  namespace: comin-dev
  labels:
    app: comin-leave-management-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: comin-leave-management-service
  template:
    metadata:
      labels:
        app: comin-leave-management-service
    spec:
      containers:
      - name: comin-leave-management-service
        image: ghcr.io/kaveeshag/comin-leave-management-service:34db0d0c17973c2e39323e4f8c0a31144e731f4f
        imagePullPolicy: Always
        ports:
        - containerPort: 8083
        env:
        - name: GO_ENV
          value: "development"
        resources:
          limits:
            cpu: "0.5"
            memory: "512Mi"
          requests:
            cpu: "0.2"
            memory: "256Mi"